// Generated by Wrangler by running `wrangler types`

interface Env {
	CSRF_TOKENS: KVNamespace;
	GH_APP: KVNamespace;
	GITHUB_OAUTH_API_URL: "https://github.com/login/oauth";
	GITHUB_GRAPHQL_API_URL: "https://api.github.com/graphql";
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_CLIENT_SECRET: string;
	GITHUB_APP_ID: string;
	GITHUB_APP_PRIVATE_KEY: string;
	GITHUB_APP_REDIRECT_URI: string;
	GITHUB_INSTALLATION_ID: string;
	GITHUB_PERSONAL_TOKEN: string;
	PUBLIC_GITHUB_GRAPHQL_API_URL: string;
	PUBLIC_GITHUB_OAUTH_API_URL: string;
	PUBLIC_WEBSITE_DOMAIN: string;
	PUBLIC_WEBSITE_URL: string;
	PUBLIC_WORKER_URL: string;
}
