// Generated by Wrangler by running `wrangler types`

interface Env {
	CSRF_TOKENS: KVNamespace;
	GH_APP: KVNamespace;
	GITHUB_OAUTH_API_URL: string;
	GITHUB_GRAPHQL_API_URL: string;
	GITHUB_PERSONAL_TOKEN: string;
	GITHUB_APP_CLIENT_SECRET: string;
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_ID: string;
	GITHUB_INSTALLATION_ID: string;
	GITHUB_APP_REDIRECT_URI: string;
	GITHUB_APP_PRIVATE_KEY: string;
	WEBSITE_URL: string;
	WORKER_URL: string;
	WEBSITE_DOMAIN: string;
}
